vestigios(sangue).
vestigios(cigarro).
vestigios(cafe).
vestigios(computador).
vestigios(caneca).
vestigios(diamante).
vestigios(ovos).
vestigios(envelope).
vestigios(lanterna).
vestigios(luvas).
vestigios(cabelo).
vestigios(gelo).
vestigios(tinta).
vestigios(inseto).
vestigios(batom).
vestigios(mapa).
vestigios(espelho).
vestigios(agulha).
vestigios(colar).
vestigios(tinta).
vestigios(cueca).
vestigios(baralho).
vestigios(dinheiro).
vestigios(rato).
vestigios(violino).
