objeto(machado).
objeto(zarabatana).
objeto(cinto).
objeto(tijolo).
objeto(castical).
objeto(faca).
objeto(motoserra).
objeto(martelo).
objeto(injecao).
objeto(chute).
objeto(veneno).
objeto(travesseiro).
objeto(corda).
objeto(fumaca).
objeto(sniper).
objeto(trofeu).
objeto(tesoura).
objeto(picareta).
objeto(gasolina).
objeto(explosivo).
objeto(vinho).
objeto(chave).
objeto(toalha).
objeto(guarda-chuva).
objeto(cobra).
