objeto(1, machado).
objeto(2, zarabatana).
objeto(3, cinto).
objeto(4, tijolo).
objeto(5, castical).
objeto(6, faca).
objeto(7, motoserra).
objeto(8, martelo).
objeto(9, injecao).
objeto(10, chute).
objeto(11, veneno).
objeto(12, travesseiro).
objeto(13, corda).
objeto(14, fumaca).
objeto(15, sniper).
objeto(16, trofeu).
objeto(17, tesoura).
objeto(18, picareta).
objeto(19, gasolina).
objeto(20, explosivo).
objeto(21, vinho).
objeto(22, chave).
objeto(23, toalha).
objeto(24, guarda-chuva).
objeto(25, cobra).